import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CollapsibleExample from "./components/navbar";
import ImportBsJS from "./installBootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sistema Odonto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <CollapsibleExample />
        <div className="app">{children}</div>

        <ImportBsJS />
      </body>
    </html>
  );
}
